### PR TITLE
Ensure example resources can be loaded.

### PR DESCRIPTION
**Pull request by KelSolaar**

### CODE REVIEW

**Comment by njsmith** [comment]
Huh. Looks correct, but I'm curious in which possible configuration the original led to problems? (Windows accepts both `\` and `/` in general.)

**Comment by KelSolaar** [comment]
Not sure either because it somehow did looked fine to me (although dodgy) but something was going wrong on my Vagrant VM, I didn't really bothered to understand and just did proper path concatenation:

```python
vagrant@precise64:/colour-science/pycam02ucs/pycam02ucs/cm$ python viscm.py
/colour-science/pycam02ucs/pycam02ucs/srgb.py:23: RuntimeWarning: invalid value encountered in power
  (1+a) * C_linear ** (1/2.4) - a])
/colour-science/pycam02ucs/pycam02ucs/srgb.py:52: RuntimeWarning: invalid value encountered in less
  if np.any(RGB < 0) or np.any(RGB > 1):
/colour-science/pycam02ucs/pycam02ucs/srgb.py:52: RuntimeWarning: invalid value encountered in greater
  if np.any(RGB < 0) or np.any(RGB > 1):
/colour-science/pycam02ucs/pycam02ucs/srgb.py:10: RuntimeWarning: invalid value encountered in less
  linear_portion = (C_srgb < 0.04045)
/colour-science/pycam02ucs/pycam02ucs/ciecam02.py:214: RuntimeWarning: invalid value encountered in less
  hprime = np.select([h < h_i[0], True], [h + 360, h])
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt4.py", line 261, in mouseReleaseEvent
    FigureCanvasBase.button_release_event( self, x, y, button )
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 1808, in button_release_event
    self.callbacks.process(s, event)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/matplotlib/cbook.py", line 527, in process
    proxy(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/matplotlib/cbook.py", line 405, in __call__
    return mtd(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/matplotlib/widgets.py", line 195, in _release
    func(event)
  File "viscm.py", line 581, in show_viscm
    self.prop_windows.append(viscm(cm, name='test_cm'))
  File "viscm.py", line 221, in __init__
    local_deltas = N * UNIFORM_SPACE.deltaEp_sRGB(RGB[:-1, :], RGB[1:, :])
  File "/colour-science/pycam02ucs/pycam02ucs/cam02ucs.py", line 66, in deltaEp_sRGB
    JMh1 = _XYZ_to_JMh(XYZ1)
  File "/colour-science/pycam02ucs/pycam02ucs/cam02ucs.py", line 113, in _XYZ_to_JMh
    ciecam02_color = vc.XYZ_to_CIECAM02(XYZ)
  File "/colour-science/pycam02ucs/pycam02ucs/ciecam02.py", line 220, in XYZ_to_CIECAM02
    / (tmp + (h_i[i + 1] - hprime) / e_i[i + 1]))
IndexError: index 5 is out of bounds for size 5
QCoreApplication::exec: The event loop is already running
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt4.py", line 261, in mouseReleaseEvent
    FigureCanvasBase.button_release_event( self, x, y, button )
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 1808, in button_release_event
    self.callbacks.process(s, event)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/matplotlib/cbook.py", line 527, in process
    proxy(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/matplotlib/cbook.py", line 405, in __call__
    return mtd(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/matplotlib/widgets.py", line 195, in _release
    func(event)
  File "viscm.py", line 581, in show_viscm
    self.prop_windows.append(viscm(cm, name='test_cm'))
  File "viscm.py", line 308, in __init__
    images.append(np.loadtxt(example_dir + "hist2d.txt"))
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/numpy/lib/npyio.py", line 734, in loadtxt
    fh = iter(open(fname, 'U'))
IOError: [Errno 2] No such file or directory: '/examples/hist2d.txt'
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt4.py", line 261, in mouseReleaseEvent
    FigureCanvasBase.button_release_event( self, x, y, button )
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 1808, in button_release_event
    self.callbacks.process(s, event)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/matplotlib/cbook.py", line 527, in process
    proxy(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/matplotlib/cbook.py", line 405, in __call__
    return mtd(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/matplotlib/widgets.py", line 195, in _release
    func(event)
  File "viscm.py", line 581, in show_viscm
    self.prop_windows.append(viscm(cm, name='test_cm'))
  File "viscm.py", line 308, in __init__
    images.append(np.loadtxt(example_dir + "hist2d.txt"))
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/numpy/lib/npyio.py", line 734, in loadtxt
    fh = iter(open(fname, 'U'))
IOError: [Errno 2] No such file or directory: '/examples/hist2d.txt'
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt4.py", line 261, in mouseReleaseEvent
    FigureCanvasBase.button_release_event( self, x, y, button )
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 1808, in button_release_event
    self.callbacks.process(s, event)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/matplotlib/cbook.py", line 527, in process
    proxy(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/matplotlib/cbook.py", line 405, in __call__
    return mtd(*args, **kwargs)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/matplotlib/widgets.py", line 195, in _release
    func(event)
  File "viscm.py", line 581, in show_viscm
    self.prop_windows.append(viscm(cm, name='test_cm'))
  File "viscm.py", line 308, in __init__
    images.append(np.loadtxt(example_dir + "hist2d.txt"))
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/numpy/lib/npyio.py", line 734, in loadtxt
    fh = iter(open(fname, 'U'))
IOError: [Errno 2] No such file or directory: '/examples/hist2d.txt'
```

**Comment by njsmith** [comment]
Ah, that explains it -- you're doing `python viscm.py` and the code is written expecting you to do `python -m pycam02ucs.cm.viscm` :-). You're ending up with `__file__` set to a relative path (just `"viscm.py"` instead of `".../viscm.py"`), and end up trying to concatenate an empty directory to the basename. `os.path.join` discards empty segments, so it ends up working.

I guess I'll go ahead and merge because it isn't wrong, but FYI you might run into other weirdnesses running it this way.

**Comment by KelSolaar** [comment]
I think I ended up running it this way because it is the way I was used to do it before the repo was ready for prime time. Cannot harm concatenating paths with `os.path.join` anyway ;)

**Comment by njsmith** [comment]
True enough :-).

Excellent work on `colour` btw! We probably would not have gone done this rabbit hole as far as we did if `colour` had existed when we started :-). And possibly we should think if there's any useful coordination possible...? I think there may be an enduring role for this package (probably under a better name) as a light-weight, minimal dependency colorspace conversion tool (see also the `magic-converter` branch that adds a simple function `cspace_convert(arr, from_space, to_space)` and automagically performs multi-step conversions), and AFAIK this package is still the only one in Python that has the CAM02-* spaces and color vision deficiency simulation. But I don't have any particular ambition to maintain a color management package forever myself, or fragment the space further...

**Comment by KelSolaar** [comment]
Thanks for the kind words! :)

A coordination would be definitely be great! I actually wanted to implement Machado paper  (http://www.inf.ufrgs.br/~oliveira/pubs_files/CVD_Simulation/CVD_Simulation.html), probably the whole model instead of the pre-computed matrices. It is a bit hectic at work these days so I don't have much time! Anyway, feel free to contact Michael or myself: http://colour-science.org/contributors.php.

**Pull request merged**
